//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by ctrlkit. DO NOT EDIT.

package manager

import (
	"context"
	apiv1 "demo/api/v1"
	"fmt"
	"github.com/arkbriar/ctrlkit/pkg/ctrlkit"
	"github.com/go-logr/logr"
	batchv1 "k8s.io/api/batch/v1"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type CronJobControllerManagerState struct {
	client.Reader
	target *apiv1.CronJob
}

func (s *CronJobControllerManagerState) GetJobs(ctx context.Context) ([]batchv1.Job, error) {
	var jobsList batchv1.JobList

	matchingLabels := map[string]string{
		"cronjob": s.target.Name,
	}
	matchingFields := map[string]string{
		".metadata.controller": s.target.Name,
	}

	err := s.List(ctx, &jobsList, client.InNamespace(s.target.Namespace),
		client.MatchingLabels(matchingLabels), client.MatchingFields(matchingFields))
	if err != nil {
		return nil, fmt.Errorf("unable to get state 'jobs': more than 1 object found")
	}

	var validated []batchv1.Job
	for _, obj := range jobsList.Items {
		if ctrlkit.ValidateOwnership(&obj, s.target) {
			validated = append(validated, obj)
		}
	}

	return validated, nil
}

func NewCronJobControllerManagerState(reader client.Reader, target *apiv1.CronJob) CronJobControllerManagerState {
	return CronJobControllerManagerState{
		Reader: reader,
		target: target,
	}
}

type CronJobControllerManagerImpl interface {
	ctrlkit.CrontollerManagerActionLifeCycleHook

	ListActiveJobsAndUpdateStatus(ctx context.Context, logger logr.Logger, jobs []batchv1.Job) (ctrl.Result, error)

	CleanUpOldJobsExceedsHistoryLimits(ctx context.Context, logger logr.Logger, jobs []batchv1.Job) (ctrl.Result, error)

	RunNextScheduledJob(ctx context.Context, logger logr.Logger) (ctrl.Result, error)

	UpdateCronJobStatus(ctx context.Context, logger logr.Logger) (ctrl.Result, error)
}

type CronJobControllerManager struct {
	state  CronJobControllerManagerState
	impl   CronJobControllerManagerImpl
	logger logr.Logger
}

func (m *CronJobControllerManager) ListActiveJobsAndUpdateStatus() ctrlkit.ReconcileAction {
	return ctrlkit.WrapAction("ListActiveJobsAndUpdateStatus", func(ctx context.Context) (ctrl.Result, error) {
		logger := m.logger.WithValues("action", "ListActiveJobsAndUpdateStatus")

		jobs, err := m.state.GetJobs(ctx)
		if err != nil {
			return ctrlkit.RequeueIfError(err)
		}

		defer m.impl.AfterActionRun("ListActiveJobsAndUpdateStatus", ctx, logger)
		m.impl.BeforeActionRun("ListActiveJobsAndUpdateStatus", ctx, logger)

		return m.impl.ListActiveJobsAndUpdateStatus(ctx, logger, jobs)
	})
}

func (m *CronJobControllerManager) CleanUpOldJobsExceedsHistoryLimits() ctrlkit.ReconcileAction {
	return ctrlkit.WrapAction("CleanUpOldJobsExceedsHistoryLimits", func(ctx context.Context) (ctrl.Result, error) {
		logger := m.logger.WithValues("action", "CleanUpOldJobsExceedsHistoryLimits")

		jobs, err := m.state.GetJobs(ctx)
		if err != nil {
			return ctrlkit.RequeueIfError(err)
		}

		defer m.impl.AfterActionRun("CleanUpOldJobsExceedsHistoryLimits", ctx, logger)
		m.impl.BeforeActionRun("CleanUpOldJobsExceedsHistoryLimits", ctx, logger)

		return m.impl.CleanUpOldJobsExceedsHistoryLimits(ctx, logger, jobs)
	})
}

func (m *CronJobControllerManager) RunNextScheduledJob() ctrlkit.ReconcileAction {
	return ctrlkit.WrapAction("RunNextScheduledJob", func(ctx context.Context) (ctrl.Result, error) {
		logger := m.logger.WithValues("action", "RunNextScheduledJob")

		defer m.impl.AfterActionRun("RunNextScheduledJob", ctx, logger)
		m.impl.BeforeActionRun("RunNextScheduledJob", ctx, logger)

		return m.impl.RunNextScheduledJob(ctx, logger)
	})
}

func (m *CronJobControllerManager) UpdateCronJobStatus() ctrlkit.ReconcileAction {
	return ctrlkit.WrapAction("UpdateCronJobStatus", func(ctx context.Context) (ctrl.Result, error) {
		logger := m.logger.WithValues("action", "UpdateCronJobStatus")

		defer m.impl.AfterActionRun("UpdateCronJobStatus", ctx, logger)
		m.impl.BeforeActionRun("UpdateCronJobStatus", ctx, logger)

		return m.impl.UpdateCronJobStatus(ctx, logger)
	})
}

func NewCronJobControllerManager(state CronJobControllerManagerState, impl CronJobControllerManagerImpl, logger logr.Logger) CronJobControllerManager {
	return CronJobControllerManager{
		state:  state,
		impl:   impl,
		logger: logger,
	}
}
